@extends('frontend.master')
@section('title')
    {{$page->seo_title}}
@stop
@section('description')
    {{$page->seo_description}}
@stop
@section('container')
    @include('frontend.hoidap.hd_header')
    @include('frontend.hoidap.hd_info')
@stop