@extends('frontend.master')
@section('title')
    {{$data['newsMain']->seo_title}}
@stop
@section('description')
    {{$data['newsMain']->seo_description}}
@stop
@section('container')
    @include('frontend.tintuc.tt_header')
    @include('frontend.tintuc.tt_info')
@stop